package com.studentservice.enums;

public enum Career {
    COMPUTER_SCIENCE,
    SOFTWARE_ENGINEERING,
    INFORMATION_SYSTEMS,
    DATA_SCIENCE,
    ARTIFICIAL_INTELLIGENCE,
    INDUSTRIAL_ENGINEERING,
    MECHANICAL_ENGINEERING,
    ELECTRICAL_ENGINEERING,
    CIVIL_ENGINEERING,
    BIOMEDICAL_ENGINEERING,
    BUSINESS_ADMINISTRATION,
    ACCOUNTING,
    ECONOMICS,
    MARKETING,
    LAW,
    MEDICINE,
    NURSING,
    PSYCHOLOGY,
    EDUCATION,
    ARCHITECTURE,
    GRAPHIC_DESIGN,
    JOURNALISM,
    INTERNATIONAL_RELATIONS,
    MATHEMATICS,
    CHEMISTRY
}
